services:
  a:
    image: nginx
    volumes:
     - ./htmlA:/usr/share/nginx/html
  b:
    image: nginx
    volumes:
     - ./htmlB:/usr/share/nginx/html
  proxy:
    image: nginx
    ports:
     - 8080:80
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf